image: docker

variables:
  DOCKER_cmsR: overlay2

services:
  - docker:dind

before_script:
  - docker login -u "$DOCKERHUB_LOGIN" -p "$DOCKERHUB_PASSWORD"

deploy:
  stage: deploy
  script:
    - docker build -t victorperin/dat-server:$CI_PIPELINE_ID .
    - docker push victorperin/dat-server:$CI_PIPELINE_ID
    - docker build -t victorperin/dat-server .
    - docker push victorperin/dat-server
  only:
    - master
