image: docker

variables:
  DOCKER_cmsR: overlay2

services:
  - docker:dind

before_script:
  - docker login -u "$DOCKERHUB_LOGIN" -p "$DOCKERHUB_PASSWORD"

deploy:
  stage: publish
  script:
    - docker build -t victorperin/docker-dat-server:$CI_PIPELINE_ID .
    - docker push victorperin/docker-dat-server:$CI_PIPELINE_ID
  only:
    - master
